import './anchor';
import './nodeIndex';
import './button';
import './ctrlLine';
import './edge';
import './edgeStart';
import './edgeEnd';
import './group';
import './groupDrag';
import './guideLine';
import './normalEnd';
import './selRect';
import './service';
import './start';
import './script';
import './artificial';
import './gatherGateway';
import './scatterGateway';
import './imageAndText'
import './textBox'
import './hider'
import './dcom'
import './danchor'
import './dsanchor'
import './output'
import './djoin'
import './dedge'
import './dmerge'
import './dgroup'
import './dfilter'
import './dpro'
import './dcustom'